### PR TITLE
Added Coursera Financial Aid Application repository as a submodule"

### PR DESCRIPTION
**Pull request by ZeeshanMukhtar1**
### Description

Added the "Coursera Financial Aid Application" repository as a submodule to provide valuable information on how to apply for financial aid on Coursera.

### Details

I've added the external repository "Coursera-Financial-Aid-Application" as a submodule in the "resources" folder of this repository. This submodule contains a comprehensive guide on how to apply for financial aid on Coursera, which can be a valuable resource for individuals looking for financial assistance to access online courses.

This contribution aims to expand the knowledge hub by including a well-maintained and informative resource for the SheSharp community and other developers who may benefit from it.

### Link

[Link to Coursera Financial Aid Application Repository](https://github.com/ZeeshanMukhtar1/Coursera-Financial-Aid-Application)

### Checklist

- [x] Added "Coursera Financial Aid Application" as a submodule.
- [x] Updated the README to include my social handels.
- [x] Verified that the submodule URL is correct.
- [x] Tested the submodule to ensure it works as expected.
- [x] Committed the changes and pushed them to my forked repository.

### Screenshots (if applicable)

[N/A]

### CODE REVIEW

**Review by mariahlaqua — COMMENTED** [review]
Hey @ZeeshanMukhtar1 thanks for this PR! I need to read to understand submodules, it's new to me. I'm pretty sure we can add this but let double check with our GitHub / open source expert @adiati98 !

Thanks for your patience, this looks like a really valuable resource. 👍

**Review by adiati98 — COMMENTED** [review]
Hey @ZeeshanMukhtar1,
Thank you for your PR!

There's a couple of notes here:

- Please make two seperate PRs as you are now making changes on two different things. I believe we have separate issues for these as well. If you don't find them, please create an issue. And don't forget to link the issue number to your PRs.
- As we're only receiving PRs from our members to add themselves to our socials page, please provide you Slack handle so we can easily confirm. Please [read the issue](https://github.com/shesharpnl/knowledge-hub/issues/14) through.
- I really like the details of your PR! However, please use our [PR templates](https://github.com/shesharpnl/.github/blob/main/.github/pull_request_template.md?plain=1) for us to review your PR better. You can add the details in the "Description".

For the `.gitmodules`:

We want to keep this repository as basic as possible. So we don't think we need it right now 🙂

However, your resource would be very valuable for our members!
So, you can add the link to your repository in our resources by:

- Create a new file called `scholarships.md` in the `resources` folder.
- Follow the format in [this file](https://github.com/shesharpnl/knowledge-hub/blob/main/resources/supportive-tech-orgs.md) to add your link to this new file.

Please let me know if you have any questions or need clarifications. :)

**Comment by ZeeshanMukhtar1** [comment]
Hi @adiati98, i made the changes as u requested  

## Assigned Issue

- [x] I am assigned to the issue number 38.

## Description

I have created a resource to assist students in securing financial aid for online courses. This resource offers a comprehensive guide on how to apply for financial aid specifically on Coursera. It is designed to support learners on their educational journey.

## Type of PR

- [ ] ✨ Feature
- [ ] 🐞 Bug fix
- [ ] 📄 Documentation update
- [x] Others

Please note that this PR falls under the "Others" category since it involves adding a new resource to the project.

**Changes Made:**

- Created a new file, "scholarships. md," in the "resources" folder to include the link to my GitHub repository.
- Provided a brief description of the resource, emphasizing its role in assisting students in accessing financial aid for online courses on Coursera.

**Additional Information:**

I've made the recommended changes based on the feedback received, including the removal of the .gitmodules file and providing the link to my resource via "scholarships.md."

This PR aligns with the project's goal of expanding the collection of resources to help the community.

### Checklist

- [x] Created "scholarships. 
Screenshot 2023-10-11 213200
md" in the "resources" folder.
- [x] Added link to the Coursera Financial Aid Application repository.
- [x] Committed the changes and pushed them to my forked repository.

### Screenshots (if applicable)


When I push this branch to my forked repository and create a PR, it will be set to automatically merge. is it the correct behavior
Screenshot 2023-10-11 213200
 as u requested, if yes plz merge it

**Comment by ZeeshanMukhtar1** [comment]
Screenshot (17)
plz ignore the above screenshort as this was accidentally uploaded ( sorry for that )  the corresponding Screenshot is attached with this comment ..plz let me know if u have any other improvements.

here is my slack handle : "Zeeshan Mukhtar" in your community

**Comment by adiati98** [comment]
Hey @ZeeshanMukhtar1,

Thank you for this changes.
However, I still can see that you're adding the socials in this PR and we don't want that :)

If this is easier for you, let's close this PR and start fresh:

- Create one PR for each purpose. One for adding resource (I added a new issue for this, issue #39) and one for adding socials. Please include your Slack handle in the PR when you add socials.

Answering your question:

> When I push this branch to my forked repository and create a PR, it will be set to automatically merge.

It's not set to automatically merge. Only maintainers can merge PRs after they review them.

Side note:
For your future reference, please pay attention to the format of your message. It's quite hard to read when there's a screenshot in between of your message :)

**Pull request closed without merging**
