### PR TITLE
feat(opensource): modified Readme

### LINKED ISSUE #33: Fix the Table of Content on the README
# Suggestion/Improvement

🌟 Hi there! We're excited to hear your suggestions and ideas for making this project better. Thank you for contributing to our community!

## Description

There is a Table of Content in the README file, however, it's quite all over the place without a title.

SheSharp TOC

## Motivation

Having a title for the Table of Content and make it a section will make the README tidier.

## Implementation (if applicable)

- Add an `h2` with text: Table of Contents.
- Remove the first `<li>` (SheSharp Knowledge Hub) as we don't need to navigate to it from the Table of Content.

### PR DESCRIPTION
**Pull request by dyaramatreya**
## Description

 
- This PR fixes the documentation to make sure the Table of Contents header is added 
- Removes unnecessary item as per the issue

## Type of PR

- [ ] ✨ Feature
- [ ] 🐞 Bug fix
- [x] 📄 Documentation update
- [ ] Others

## Related Issue

- Closes #33

### CODE REVIEW

**Comment by mariahlaqua** [comment]
Hello @dyaramatreya , thanks for opening this PR. We are working on improving our contributing guidelines to reflect that issues must be assigned first, before we approve a pull request. We also prioritise assigning issues to our community members and to underrepresented genders. You can learn more about our mission on our [website](https://www.shesharp.co), or join our [slack](https://www.shesharp.co/slack).

**Comment by dyaramatreya** [comment]
> Hello @dyaramatreya , thanks for opening this PR. We are working on improving our contributing guidelines to reflect that issues must be assigned first, before we approve a pull request. We also prioritise assigning issues to our community members and to underrepresented genders. You can learn more about our mission on our [website](https://www.shesharp.co), or join our [slack](https://www.shesharp.co/slack).

Hello @mariahlaqua. That's great.
Anyway, I have also asked for assigning the issue to me in the issue comments. If possible and in case of no representation from the above mentioned communities and members, I'll be happy to get my contribution counted 😄.
Thanks

**Comment by adiati98** [comment]
Hi @dyaramatreya,
Thank you for the PR!

We are merging this with a consideration that you have asked to be assigned to the issue.
But for your future reference, please wait until a maintainer assign you to the issue before you make changes and create a PR.
Doing so will cause your PR won't get merged. :)

**Comment by mariahlaqua** [comment]
Thanks for your contribution, patience, and understanding @dyaramatreya ! We will have our documentation updated shortly to reflect the community guidelines better. :)

**Comment by dyaramatreya** [comment]
> Hi @dyaramatreya, Thank you for the PR!
> 
> We are merging this with a consideration that you have asked to be assigned to the issue. But for your future reference, please wait until a maintainer assign you to the issue before you make changes and create a PR. Doing so will cause your PR won't get merged. :)
> 
> cc: @mariahlaqua

Thanks @adiati98

**Comment by mariahlaqua** [comment]
Thanks @dyaramatreya !! We appreciate your patience and understanding. We've also added a label "no-assignment-necessary" for issues where this is not a requirement.

**Pull request merged**
